# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-14 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('first_message', models.CharField(max_length=3000)),
                ('pos_message', models.CharField(max_length=3000)),
                ('neg_message', models.CharField(max_length=3000)),
            ],
        ),
    ]
